name: CI - Elixir Tests

on:
  push:
    branches: [feature/teslamate_weather]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/elixir_test.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}